### ISSUE TITLE
Stashes don't auto complete on plugin.

### ISSUE THREAD

**Issue by forfiet2** [larsvansoest/emote-clue-items#73]
Why doesn't the plugin automatically check off the stashes when done? I had to manually click one as filled. [https://i.imgur.com/4t14w1S.png](https://github.com/larsvansoest/emote-clue-items/issues/url) I checked it to make sure. I have to click the box to make it green instead of the white box on the side panel for the plugin.

**Comment by larsvansoest** [comment]
Unfortunately, RuneLite does not support checking stash fill statuses (see https://github.com/runelite/runelite/issues/1662). So, the list cannot be autocompleted by reading fill statuses from the client. 

Because the stash fill status issue is [tracked](https://github.com/runelite/runelite/issues/1662), I was hoping it would be solved eventually.

An alternative solution is to monitor the chat for a stash unit withdraw/deposit message. When such a message occurs, the plugin could autocomplete for the stash unit closest to the player within a certain range. However, as soon as the player switches to the vanilla client or mobile, any stash updates will not be autocompleted. Consequently, the next time the player logs into RuneLite, the list will represent the fill statuses incorrectly. Therefore, I would argue the alternative solution would only a new inconvenience.



If the alternative solution is still desired, it could be implemented as an optional feature.

Regardless, thanks for your suggestion! New ideas are always appreciated.
